### PR TITLE
Fixed TimeSpan and DateTime

### LINKED ISSUE #500: TimeSpan doesn't work.
Problem: 
2>Build FAILED.
Build has been canceled.

Example taken from: https://msdn.microsoft.com/en-us/library/system.timespan(v=vs.110).aspx

Code that doesn't work:
TimeSpan interval = new TimeSpan(2, 14, 18);
Console.WriteLine(interval.ToString());

TestCase(Project): http://dropmefiles.com/XXfuP

### PR DESCRIPTION
**Pull request by jp2masa**
Fixes #500.

## Changes
- Fixed TimeSpan and DateTime.
- Added tests.

Depends on CosmosOS/IL2CPU#54.

### CODE REVIEW

File: source/Cosmos.Core_Plugs/System/DateTimeImpl.cs [hunk 1]
```diff
@@ -1,68 +0,0 @@
...
-                BCDtoBIN(raw[0]) //SECOND
-            );
-        }
-
-        // TODO: get timezone
-        public static DateTime get_UtcNow() => get_Now();
-
-        private static int[] GetRawDate()
-        {
-            IOPort p70 = new IOPort(0x70);
```
Comment (Arawn-Davies) [inline source/Cosmos.Core_Plugs/System/DateTimeImpl.cs]: I think these IOPorts are already in the RTC IOGroup, would it be better to just use those instead of making a new instance of these?

Comment (jp2masa) [reply source/Cosmos.Core_Plugs/System/DateTimeImpl.cs]: Those are removed lines. I moved the plug to System and it uses RTC from HAL.

Comment (Arawn-Davies) [reply source/Cosmos.Core_Plugs/System/DateTimeImpl.cs]: Oh right didn't notice :') thanks for pointing that out
